### ISSUE TITLE
Spring Boot - Error handling multi values in "RequestMaping"

### ISSUE THREAD

**Issue by xiujunma** [JetBrains/kotless#72]
```java
@RestController
@RequestMapping("/user")
class UserController(
    @Autowired val userRepository: UserRepository
) {
    @GetMapping(value =["/", ""]) // <- Not able to handle this.
    fun all():Iterable<User> {
        return userRepository.findAll()
    }
}
```

**Execution failed for task ':generate'.
List has more than one element.**

**Comment by kad-leeuwg1** [comment]
This message seems to be caused by the call to `currentPath.single()` in https://github.com/JetBrains/kotless/blob/master/dsl/spring/spring-lang-parser/src/main/kotlin/io/kotless/parser/spring/processor/route/SpringAnnotationUtils.kt#L48.

Note that there is an explicit check for methods annotated with `RequestMapping` at [line 54](https://github.com/JetBrains/kotless/blob/master/dsl/spring/spring-lang-parser/src/main/kotlin/io/kotless/parser/spring/processor/route/SpringAnnotationUtils.kt#L54).

**Comment by xiujunma** [comment]
> This message seems to be caused by the call to `currentPath.single()` in https://github.com/JetBrains/kotless/blob/master/dsl/spring/spring-lang-parser/src/main/kotlin/io/kotless/parser/spring/processor/route/SpringAnnotationUtils.kt#L48.
> 
> Note that there is an explicit check for methods annotated with `RequestMapping` at [line 54](https://github.com/JetBrains/kotless/blob/master/dsl/spring/spring-lang-parser/src/main/kotlin/io/kotless/parser/spring/processor/route/SpringAnnotationUtils.kt#L54).

Should it call the explicit check before the `currentPath.single()`?

**Comment by TanVD** [comment]
Yep, thanks!
