### ISSUE TITLE
Ktor features missing?!

### ISSUE THREAD

**Issue by BlackHornet** [JetBrains/kotless#81]
Hello,

first of all: Kotless is awesome 👍 

As I'm using the ktor-lang for development I wonder if it is planned to support ktor Locations (afaik those are not added to the API Gateway in AWS).

In addition I wonder if it would be possible to add something like the Events API to the ktor-lang?!
So it is possible to define additional periodic "tasks" in my project (e.g. download some kind of daily generated content to be cached in a S3 bucket, instead of fetching it everytime a lambda is called).

Regards

**Comment by icehockeystar** [comment]
you can use `@Scheduled` annotation https://site.kotless.io/pages/dsl/events

**Comment by BlackHornet** [comment]
Ah I see, I had to define DSL manually, so I could add kotless-lang and ktor-lang 👍 
Thanks

**Comment by icehockeystar** [comment]
sorry man, I realized the problem later as well. What's the problem to add Scheduled event to the `ktor-lang` and `spring-boot-lang` ?
My actual problem is that I want to have something like dependency injections in a project. This is not possible with kotless-lang, since everything is based on functions or objects there. I hoped that with ktor-lang I could use Koin or with spring-boot-lang the normal DI. But it seems that everything is based on objects and functions? Any ideas on it?

**Comment by TanVD** [comment]
Hey, yes as for the `@Scheduled` -- right now it is available in Kotless only and for Ktor I have to invent something based on functions. As for the dependency injection, you can use it in `ktor-lang`.. I don't know the reason why it should not be working... :)

**Comment by BlackHornet** [comment]
@icehockeystar koin is not a problem, just initialize it in prepare function of your Kotless class.

After that you can use by inject within any route to inject your desired class instances.
